apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: nginx:container
      image: latest
      volumeMounts:
          - mountPath: /volume-inside-container
            name: first-pv
  volumes:
    - name: first-pv
      PersistentVolumeClaim:
        claimName: pvc-1